name = "nav"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_CLIENT_ID = "Ov23liHmhUEW4VDB54vd"
GITHUB_OWNER = "vrain1025"
GITHUB_REPO = "navsphere-data"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://nav.xinyangai.com/api/auth"
NEXT_PUBLIC_API_URL="https://nav.xinyangai.com"

